package com.gerenciamentoit.acesso.domain;

public enum Permissao {
    SETOR_CRIAR,
    SETOR_VISUALIZAR,
    TURNO_CRIAR,
    TURNO_VISUALIZAR,
    USUARIO_CRIAR,
    USUARIO_VISUALIZAR,
    USUARIO_ATRIBUIR_ACESSO,
    TIPO_ATIVO_GERENCIAR,
    TIPO_ATIVO_VISUALIZAR,
    ATIVO_CADASTRAR,
    ATIVO_VISUALIZAR,
    ATIVO_LIBERAR,
    ATIVO_CORRIGIR_IDENTIFICACAO,
    AUDITORIA_VISUALIZAR
}
